version: '3.8' # Especifica a versão do Docker Compose

services:
  mongo-local:
    image: mongo:latest 
    container_name: mongodb_local_dev 
    
    ports:
      - "27017:27017"
      
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      
      MONGO_INITDB_DATABASE: auth-app-db 
      
    volumes:
      - mongo-data:/data/db
      
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 123456

      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: mongo-local
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo-local:27017/auth-app-db?authSource=admin
    depends_on:
      - mongo-local
volumes:
  mongo-data:
    driver: local 